version: "3.9"
services:
  nginx: 
    image: nginx:alpine
    container_name: nginx
    ports:
    - target: 80
      published: 80
    volumes:
    - type: bind
      source: ./nginx/nginx.conf
      target: /etc/nginx/nginx.conf
  flask-app:
    container_name: flask-app
    image: trio-task-flask:latest
    build: ./flask-app
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
  # mysql:
  #   container_name: mysql
  #   image: dougiescoolregistry.azurecr.io/trio-task-db:latest
  #   build: ./db
  #   environment:
  #     MYSQL_ROOT_PASSWORD:  my-password
  #     MYSQL_DATABASE: flask-db
      

